### DISCUSSION TITLE
Hi, I'm stuck in either index homepage or blog home page

### DISCUSSION THREAD

**Discussion by khorshid1974** [arthelokyo/astrowind#303] [General]
Hi, I'm stuck in either index homepage or blog home page, which can be switched from config.yaml 
```
apps:
  blog:
    isEnabled: true
    postsPerPage: 6
```
I want to have my default index page and still have the /blog

**Comment by prototypa** [comment]
Hi @khorshid1974 

If you want to have your index page (somedomain.com/) and also a route for the blog (somedomain.com/blog) we suggest a configuration like the following:

```yaml
# (...)

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: 'blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'blog/category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'blog/tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

# (...)
```

If you have any other questions or problems, please let us know.
