### DISCUSSION TITLE
Building the site works though deployed site has CORS errors

### DISCUSSION THREAD

**Discussion by mainangethe** [arthelokyo/astrowind#454] [Q&A] [answered]
### Issue
- I'm deploying a landing page I've used astrowind to design to a shared server on Dreamhost.
- The site builds and I'm able to get the files
- Deployed site though fails to load any of the files including css.

### Expected Result
![Screenshot 2024-05-17 at 14 39 55](https://github.com/onwidget/astrowind/assets/41260290/1dfeb1f4-278b-46da-993b-d9a0622447cf)

### Actual Result
![Screenshot 2024-05-17 at 14 42 34](https://github.com/onwidget/astrowind/assets/41260290/372d95d7-39ed-429c-a1b3-fdf3c0b4930b)

**Comment by prototypa** [comment]
Hi @mainangethe 

If you do an `npm run build` of the project and it generates a _dist_ folder and the generated content is ok, then the behavior related to the 404 error is something that you need to configure in _DreamHost_ or some specific configuration of your project. I'm moving this to 

Discussions since it's not a specific issue with **AstroWind**.

**Comment by mainangethe** [comment]
The generated content is not okay. The behaviour is also appearing in the dist folder locally.
let me share my config

```
site:
  name: Kijiji Nuts
  site: 'https://kijijinuts.co.ke'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: #

# Default SEO metadata
metadata:
  title:
    default: Kijiji Nuts
  description: "We are becoming one of the best fruit processing plants in Kenya"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Kijiji Nuts
    type: website
  twitter:
    handle: 'mradi_ke'
    site: 'https://mradi.co.ke'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
```
