### DISCUSSION TITLE
GA?

### DISCUSSION THREAD

**Discussion by jeffkershner** [arthelokyo/astrowind#621] [Q&A]
I added the GA number to the .yaml:
```
analytics:
  vendors:
    googleAnalytics:
      id: 'G-64TJ51XRS5'
```

Weird... Google Analytics says it detects the GA script on my side, but after a week, I still see no analytics being collected.

I deployed to CloudPages.  Do I have to do anything else?
