### ISSUE TITLE
Cannot read properties of undefined (reading 'currentPage')

### ISSUE THREAD

**Issue by aluminum-ice** [arthelokyo/astrowind#575]
Disabling the blog through the `config.yaml`

```
apps:
  blog:
    isEnabled: false
    postsPerPage: 6
```
causes a TypeError:
<img width="1116" alt="Screenshot 2024-12-25 at 10 46 44 PM" src="https://github.com/user-attachments/assets/817beafa-dd17-44b3-a3af-fddc9b3e4427" />

This error began for me once I updated to astro v5.0.5. I am unsure how to resolve it. Has anyone had the same issue?
